@echo off
chcp 65001 >nul
echo [1/4] 检查 MySQL 服务...
mysqladmin -u root -p%DB_PASSWORD% ping >nul 2>&1 || (echo 请先启动 MySQL 服务 & pause & exit /b)
echo [2/4] 初始化数据库...
mysql -u root -p%DB_PASSWORD% < database\init_db.sql
echo [3/4] 启动后端 (http://localhost:8080)...
start "pams-backend" cmd /k "cd /d %~dp0pams-backend && mvn spring-boot:run"
echo [4/4] 启动前端 (http://localhost:3000)...
start "pams-web" cmd /k "cd /d %~dp0pams-web && npm run dev"
timeout /t 15 >nul
start http://localhost:3000
